### ISSUE TITLE
Enable pedantic tests

### ISSUE THREAD

**Issue by Flamefire** [boostorg/io#9]
As this library is pretty much self-contained I'd recommend to enable pedantic warnings and Werror by adding 

```
project : requirements
  <warnings>pedantic
  <warnings-as-errors>on ;
```

to the top of the test/Jamefile.v2. This allows downstream projects to build with the same warning level and avoids surprises later when a user is using a higher warning level. Additionally it gives some protection against bugs the compiler can catch easily.

Example problem for downstream: https://github.com/boostorg/io/commit/e276f63390a225df3af442889258078f9be27cdb#diff-a03a32e4bb8dfbae73e4d575219a7f0eR15 has a trailing semicolon 

Thanks a lot!

**Comment by glenfe** [comment]
Done in aa70414fde0c3b337dcaa849b61241efd581a5f4.
